/-
  Orion/GradedOrderCombinatorics/LevelSets.lean

  Graded Order Combinatorics — Layer 1: Level Sets and Basic Properties
  Generated by Library Weaver.
-/

import Mathlib

namespace Orion.GradedOrderCombinatorics

-- Definitions and proofs below are generated by the Proof Oracle.

noncomputable def level (α : Type*) [Fintype α] [DecidableEq α] [Preorder α] [GradeOrder ℕ α] (k : ℕ) : Finset α :=
  Finset.univ.filter (fun x => grade ℕ x = k)

theorem levelCard_sum [Fintype α] [DecidableEq α] [Preorder α] [GradeOrder ℕ α] :
    ∑ k ∈ (Finset.univ : Finset α).image (grade ℕ), (Finset.univ.filter (fun x : α => grade ℕ x = k)).card =
    Fintype.card α :=
  (Finset.card_eq_sum_card_image (grade ℕ) (Finset.univ : Finset α)).symm.trans Finset.card_univ

theorem level_mem_iff [Fintype α] [DecidableEq α] [Preorder α] [GradeOrder ℕ α] (x : α) (k : ℕ) : x ∈ level α k ↔ grade ℕ x = k := by
  unfold level
  simp [Finset.mem_filter, Finset.mem_univ]

theorem level_disjoint [Fintype α] [DecidableEq α] [Preorder α] [GradeOrder ℕ α] {k₁ k₂ : ℕ} (h : k₁ ≠ k₂) : Disjoint (level α k₁) (level α k₂) := by
  rw [Finset.disjoint_left]
  intro x hx1 hx2
  rw [level_mem_iff] at hx1 hx2
  exact h (hx1.symm.trans hx2)

theorem level_nonempty [Fintype α] [Preorder α] [GradeOrder ℕ α] (k : ℕ) (h : ∃ x : α, grade ℕ x = k) : (Finset.univ.filter (fun (x : α) => grade ℕ x = k)).Nonempty := by
  obtain ⟨x, hx⟩ := h
  exact ⟨x, Finset.mem_filter.mpr ⟨Finset.mem_univ x, hx⟩⟩

-- Note: inner Finset.univ annotated as Finset α to fix GradeOrder typeclass resolution
theorem level_union [Fintype α] [DecidableEq α] [Preorder α] [GradeOrder ℕ α] : Finset.biUnion ((Finset.univ : Finset α).image (grade ℕ)) (fun k => (Finset.univ : Finset α).filter (fun x => grade ℕ x = k)) = Finset.univ := by
  ext x
  constructor
  · intro _
    exact Finset.mem_univ x
  · intro _
    apply Finset.mem_biUnion.mpr
    exact ⟨grade ℕ x, Finset.mem_image_of_mem (grade ℕ) (Finset.mem_univ x),
           Finset.mem_filter.mpr ⟨Finset.mem_univ x, rfl⟩⟩

end Orion.GradedOrderCombinatorics
