/-
  Orion/GradedOrderCombinatorics/SaturatedChains.lean

  Graded Order Combinatorics — Layer 3: Saturated Chains and Maximal Chains
  Generated by Library Weaver.
-/

import Mathlib

namespace Orion.GradedOrderCombinatorics

-- Definitions and proofs below are generated by the Proof Oracle.

theorem saturatedChain_length [Preorder α] [GradeMinOrder ℕ α] (l : List α)
    (hl : l.IsChain (· ⋖ ·)) (hne : l ≠ []) :
    grade ℕ (l.getLast hne) = grade ℕ (l.head hne) + (l.length - 1) := by
  induction l with
  | nil => exact absurd rfl hne
  | cons a t ih =>
    cases t with
    | nil => simp
    | cons b rest =>
      have hne' : b :: rest ≠ [] := List.cons_ne_nil _ _
      have htail : (b :: rest).IsChain (· ⋖ ·) := List.IsChain.tail hl
      have hrel : a ⋖ b := List.IsChain.rel_head hl
      have ih' := ih htail hne'
      have hgrad : grade ℕ a + 1 = grade ℕ b :=
        Order.covBy_iff_add_one_eq.mp (hrel.grade (𝕆 := ℕ))
      rw [show (a :: b :: rest).getLast hne = (b :: rest).getLast hne' from
        List.getLast_cons hne']
      simp only [List.head_cons, List.length_cons] at ih' ⊢
      omega

theorem saturatedChain_exists [PartialOrder α] [GradeMinOrder ℕ α] (a b : α) (hab : a ≤ b) :
    ∃ (l : List α) (hne : l ≠ []),
      l.IsChain (· ⋖ ·) ∧ l.head hne = a ∧ l.getLast hne = b := by
  -- WellFoundedLT α and IsStronglyAtomic α are automatic from GradeMinOrder ℕ α
  -- Strong induction on the grade gap
  suffices h : ∀ n, ∀ a b : α, a ≤ b → grade ℕ b - grade ℕ a = n →
      ∃ (l : List α) (hne : l ≠ []),
        l.IsChain (· ⋖ ·) ∧ l.head hne = a ∧ l.getLast hne = b from
    h _ a b hab rfl
  intro n
  induction n using Nat.strongRecOn with
  | ind n ih =>
    intro a b hab hgap
    obtain rfl | hlt := eq_or_lt_of_le hab
    · -- Base case: a = b, chain is [a]
      exact ⟨[a], List.cons_ne_nil _ _, List.isChain_singleton _, rfl, rfl⟩
    · -- Inductive case: a < b, find c with a ⋖ c ≤ b
      obtain ⟨c, hac, hcb⟩ := exists_covBy_le_of_lt hlt
      have hgac : grade ℕ c = grade ℕ a + 1 :=
        (Order.covBy_iff_add_one_eq.mp (hac.grade (𝕆 := ℕ))).symm
      have hga_lt_gb : grade ℕ a < grade ℕ b := grade_strictMono hlt
      have hgap' : grade ℕ b - grade ℕ c < n := by omega
      obtain ⟨l, hne, hchain, hhead, hlast⟩ := ih _ hgap' c b hcb rfl
      refine ⟨a :: l, List.cons_ne_nil _ _, ?_, rfl, ?_⟩
      · -- Chain': a ⋖ l.head ∧ l is a chain
        subst hhead
        exact List.IsChain.cons_of_ne_nil hne hchain hac
      · -- getLast (a :: l) = b
        rw [List.getLast_cons hne]
        exact hlast

theorem saturatedChain_length_const [Preorder α] [GradeMinOrder ℕ α] (c₁ c₂ : List α)
    (hc₁ : c₁.IsChain (· ⋖ ·)) (hc₂ : c₂.IsChain (· ⋖ ·))
    (hne₁ : c₁ ≠ []) (hne₂ : c₂ ≠ [])
    (hhead : c₁.head hne₁ = c₂.head hne₂) (hlast : c₁.getLast hne₁ = c₂.getLast hne₂) :
    c₁.length = c₂.length := by
  have h₁ := saturatedChain_length c₁ hc₁ hne₁
  have h₂ := saturatedChain_length c₂ hc₂ hne₂
  rw [hhead, hlast] at h₁
  have hlen₁ : 0 < c₁.length := by rcases c₁ with _ | _; exact absurd rfl hne₁; exact Nat.succ_pos _
  have hlen₂ : 0 < c₂.length := by rcases c₂ with _ | _; exact absurd rfl hne₂; exact Nat.succ_pos _
  omega

theorem grade_le_of_chain [Preorder α] [GradeMinOrder ℕ α] (l : List α)
    (hl : l.IsChain (· ⋖ ·)) (hne : l ≠ []) :
    grade ℕ (l.head hne) ≤ grade ℕ (l.getLast hne) := by
  have h := saturatedChain_length l hl hne
  omega

theorem saturatedChain_length_grade_diff [Preorder α] [GradeMinOrder ℕ α] (l : List α)
    (hl : l.IsChain (· ⋖ ·)) (hne : l ≠ []) :
    l.length = grade ℕ (l.getLast hne) - grade ℕ (l.head hne) + 1 := by
  have h := saturatedChain_length l hl hne
  have hle := grade_le_of_chain l hl hne
  have hlen : 0 < l.length := by rcases l with _ | _; exact absurd rfl hne; exact Nat.succ_pos _
  omega

theorem saturatedChain_grade_strictMono [Preorder α] [GradeMinOrder ℕ α] (l : List α)
    (hl : l.IsChain (· ⋖ ·)) : l.Pairwise (fun a b => grade ℕ a < grade ℕ b) := by
  induction l with
  | nil => exact List.Pairwise.nil
  | cons a t ih =>
    apply List.Pairwise.cons
    · intro b hb
      cases t with
      | nil => simp at hb
      | cons c rest =>
        have hac : a ⋖ c := List.IsChain.rel_head hl
        have hgrade_ac : grade ℕ a < grade ℕ c := grade_strictMono hac.lt
        rcases List.mem_cons.mp hb with rfl | hb_rest
        · exact hgrade_ac
        · have hpair_tail := (List.pairwise_cons.mp (ih (List.IsChain.tail hl))).1
          exact lt_trans hgrade_ac (hpair_tail b hb_rest)
    · exact ih (List.IsChain.tail hl)

-- Using l.IsChain (· ⋖ ·) instead of the suggested l.Chain' (· ⋖ ·) for consistency
-- with the rest of this file (Chain' is deprecated; IsChain is the current API).
theorem saturatedChain_nodup [Preorder α] [GradeMinOrder ℕ α] (l : List α)
    (hl : l.IsChain (· ⋖ ·)) : l.Nodup := by
  rw [List.nodup_iff_pairwise_ne]
  apply (saturatedChain_grade_strictMono l hl).imp
  intro a b h heq
  subst heq
  exact lt_irrefl _ h

end Orion.GradedOrderCombinatorics
