/-
  Orion/OracleTests/DivModUnique.lean

  Test file for Proof Oracle: uniqueness of Euclidean division.
  Self-contained — can be removed after verification.
-/

import Mathlib

namespace Orion.OracleTests.DivModUnique

-- Proof below this line is generated by the Proof Oracle.

theorem div_mod_unique (n d q r q' r' : Nat) (hd : d > 0) (h1 : n = d*q + r) (hr : r < d) (h2 : n = d*q' + r') (hr' : r' < d) : q = q' ∧ r = r' := by
  have h1' : n / d = q ∧ n % d = r := (Nat.div_mod_unique hd).mpr ⟨by linarith, hr⟩
  have h2' : n / d = q' ∧ n % d = r' := (Nat.div_mod_unique hd).mpr ⟨by linarith, hr'⟩
  exact ⟨h1'.1.symm.trans h2'.1, h1'.2.symm.trans h2'.2⟩

end Orion.OracleTests.DivModUnique
