/-
  Orion/OracleTests/GradeBotEqZero.lean

  Test file for Proof Oracle: grade of ⊥ equals 0 in a ℕ-graded order.
  Self-contained — can be removed after verification.
-/

import Mathlib

namespace Orion.OracleTests.GradeBotEqZero

-- Proof below this line is generated by the Proof Oracle.

theorem grade_bot_eq_zero [Preorder α] [OrderBot α] [GradeMinOrder ℕ α] : grade ℕ (⊥ : α) = 0 :=
  grade_bot

end Orion.OracleTests.GradeBotEqZero
