/-
  Orion/OracleTests/LevelCardSum.lean

  Test file for Proof Oracle: sum of level cardinalities equals total cardinality.
  Self-contained — can be removed after verification.
-/

import Mathlib

namespace Orion.OracleTests.LevelCardSum

-- Proof below this line is generated by the Proof Oracle.

theorem levelCard_sum [Fintype α] [DecidableEq α] [Preorder α] [GradeOrder ℕ α] :
    ∑ k ∈ (Finset.univ : Finset α).image (grade ℕ), (Finset.univ.filter (fun x : α => grade ℕ x = k)).card =
    Fintype.card α :=
  (Finset.card_eq_sum_card_image (grade ℕ) (Finset.univ : Finset α)).symm.trans Finset.card_univ

end Orion.OracleTests.LevelCardSum
