/-
  Orion/OracleTests/RankGenPolyEvalOne.lean

  Test file for Proof Oracle: evaluating the rank generating polynomial at 1
  gives the total cardinality of the poset.
  Self-contained — can be removed after verification.
-/

import Mathlib

namespace Orion.OracleTests.RankGenPolyEvalOne

-- Proof below this line is generated by the Proof Oracle.

noncomputable def rankGenPoly (α : Type*) [Fintype α] [DecidableEq α] [Preorder α] [GradeOrder ℕ α] : Polynomial ℕ :=
  ∑ k ∈ (Finset.univ : Finset α).image (grade ℕ), (Finset.univ.filter (fun x : α => grade ℕ x = k)).card • (Polynomial.X ^ k)

theorem rankGenPoly_eval_one (α : Type*) [Fintype α] [DecidableEq α] [Preorder α] [GradeOrder ℕ α] :
    Polynomial.eval 1 (rankGenPoly α) = Fintype.card α := by
  unfold rankGenPoly
  rw [Polynomial.eval_finset_sum]
  simp only [Polynomial.eval_smul, Polynomial.eval_pow, Polynomial.eval_X, one_pow, smul_eq_mul, mul_one]
  exact (Finset.card_eq_sum_card_image (grade ℕ) (Finset.univ : Finset α)).symm.trans Finset.card_univ

end Orion.OracleTests.RankGenPolyEvalOne
