/-
  Orion/OracleTests/SaturatedChainLength.lean

  Test file for Proof Oracle: saturated chain length in a ℕ-graded order.
  Self-contained — can be removed after verification.
-/

import Mathlib

namespace Orion.OracleTests.SaturatedChainLength

-- Proof below this line is generated by the Proof Oracle.

theorem saturatedChain_length [Preorder α] [GradeMinOrder ℕ α] (l : List α)
    (hl : l.Chain' (· ⋖ ·)) (hne : l ≠ []) :
    grade ℕ (l.getLast hne) = grade ℕ (l.head hne) + (l.length - 1) := by
  induction l with
  | nil => exact absurd rfl hne
  | cons a t ih =>
    cases t with
    | nil => simp
    | cons b rest =>
      have hne' : b :: rest ≠ [] := List.cons_ne_nil _ _
      have htail : (b :: rest).Chain' (· ⋖ ·) := List.IsChain.tail hl
      have hrel : a ⋖ b := List.IsChain.rel_head hl
      have ih' := ih htail hne'
      have hgrad : grade ℕ a + 1 = grade ℕ b :=
        Order.covBy_iff_add_one_eq.mp (hrel.grade (𝕆 := ℕ))
      rw [show (a :: b :: rest).getLast hne = (b :: rest).getLast hne' from
        List.getLast_cons hne']
      simp only [List.head_cons, List.length_cons] at ih' ⊢
      omega

end Orion.OracleTests.SaturatedChainLength
