/-
  Orion/OracleTests/SumRangeId.lean

  Test file for Proof Oracle: closed form for sum of 0..n.
  Self-contained — can be removed after verification.
-/

import Mathlib

open Finset

namespace Orion.OracleTests.SumRangeId

-- Proof below this line is generated by the Proof Oracle.

theorem sum_range_id (n : Nat) : (Finset.range (n+1)).sum id = n*(n+1)/2 := by
  have h := Finset.sum_range_id (n + 1)
  simp only [Nat.add_sub_cancel] at h
  -- h : ∑ i ∈ range (n+1), i = (n+1) * n / 2
  show ∑ i ∈ Finset.range (n + 1), i = n * (n + 1) / 2
  rw [h, mul_comm (n + 1) n]

end Orion.OracleTests.SumRangeId
