/-
  Orion/Combinatorics/FiniteDifference.lean

  Forward difference operator and its basic properties.
  Part of the discrete finite differences pocket identified by Edge Finder.

  The forward difference operator Δf(n) = f(n+1) - f(n) is the discrete
  analogue of the derivative. This file establishes the definition and
  basic algebraic properties (linearity, constants, etc.).

  Definition (fwdDiff) is written manually. Proofs of properties are
  generated by the Proof Oracle pipeline.
-/

import Mathlib

namespace Orion.Combinatorics.FiniteDifference

/-- The forward difference operator: Δf(n) = f(n+1) - f(n). -/
def fwdDiff (f : ℕ → ℤ) (n : ℕ) : ℤ := f (n + 1) - f n

-- Proofs below this line are generated by the Proof Oracle.
-- Do not edit the fwdDiff definition above.

theorem fwdDiff_linear (a b : ℤ) (f g : ℕ → ℤ) (n : ℕ) : fwdDiff (fun i => a * f i + b * g i) n = a * fwdDiff f n + b * fwdDiff g n := by
  simp [fwdDiff]; ring

end Orion.Combinatorics.FiniteDifference
